### ISSUE TITLE
Remove all the unnecessary comments

### ISSUE THREAD

**Issue by gaal1le0** [AslanSN/traffic-light#2]
https://github.com/AslanSN/traffic-light/blob/4feb1ed7ed9cdbdb226d7465f7bc1eecdae894a4/src/js/index.js#L1.

Please don't forget that unnecessary comment which not bring any important information should be remove, it's confused a lot because I know that the following sentence import a component.

```js
import Home from '../home.jsx'
```

Please remove this comments. It's so important :) 
You must review all the files on this project to accomplish this task :)

**Comment by AslanSN** [comment]
Okay, I've deleted all the comments because in this specific case I think they wasn't necessary. Review the pull request done for the bug branch and tell me please if it's just right. 

Thank you Manu!

**Comment by gaal1le0** [comment]
It's already merged.

**Comment by AslanSN** [comment]
Thanks!
